#version: '3.8'
#
#services:
#  mongodb:
#    image: mongo:latest
#    container_name: my-mongodb-container
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./data:/data/db
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - my-network

  mongo-seed:
    container_name: init-mongo-db
    build: ./mongodb/mongo-seed
    depends_on:
      - mongodb
    networks:
      - my-network

  flask-api:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network: